module.exports = {
   testEnvironment: "node",
   collectCoverage: true,
   coverageDirectory: "coverage",
   coverageReporters: ["text", "lcov", "html", "clover"],
   collectCoverageFrom: [
      "**/*.js",
      "!**/node_modules/**",
      "!**/coverage/**",
      "!**/_test_/**",
      "!**/tests/**",
      "!**/test/**",
      "!jest.config.js",
      "!**/index.js",
      "!**/config/**",
      "!**/seeders/**",
      "!**/migrations/**",
      "!**/bin/**",
      "!**/controllers/midTransController.js**",
      "!**/helpers/lib.js**",
   ],
   coverageThreshold: {
      global: {
         branches: 90,
         functions: 90,
         lines: 90,
         statements: 90,
      },
   },
   testPathIgnorePatterns: ["/node_modules/", "/coverage/", "/bin/"],
   setupFilesAfterEnv: [],
   testTimeout: 30000,
   forceExit: true,
   detectOpenHandles: true,
   runInBand: true,
};
